services:
  - type: web
    name: empleados-horario-backend
    env: node
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        value: tu_secreto_jwt
    staticPublishPath: ./public
